name: Create digest
description: Creates a digest of recent activity in the repo
inputs:
  token:
    description: GitHub token
    default: ${{ github.token }}
runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ inputs.token }}