name: Issue form
description: Create an issue for the CMake Tools extension.
body:
- type: markdown
  attributes:
    value: |
      ### Is there an existing issue for this?
      Please search our [existing issues](https://github.com/microsoft/vscode-cmake-tools/issues) to see if an issue already exists for the issue you'd like to report.
- type: textarea
  attributes:
    label: Brief Issue Summary
    description: |
      Put a short summary here.
      If this is a bug, please provide clear instructions as to how we can reproduce the issue on our end.
  validations:
    required: true
- type: textarea
  attributes:
    label: CMake Tools Diagnostics
    description: |
      For bugs, please run the `CMake: Log Diagnostics` command and paste the output here.
    render: shell
  validations:
    required: false
- type: textarea
  attributes:
    label: Debug Log
    description: |
      For bugs, we would also appreciate it if you used the `"cmake.loggingLevel": "debug"` setting and paste the CMake/Build output from the OUTPUT window.
    render: shell
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Information
    description: |
      Optionally provide other information that will give us more context about the issue you are encountering.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
