name: Feature request form
description: Create a feature request for the CMake Tools extension.
title: "[Feature] "
labels:
  - "enhancement"
  - "triage"
body:
- type: markdown
  attributes:
    value: |
      ### Is there an existing request for this?
      Please search our [existing issues](https://github.com/microsoft/vscode-cmake-tools/issues) to see if an issue already exists for the issue you'd like to report.
- type: textarea
  attributes:
    label: Request Overview
    description: |
      Please give us an overview of the feature you would like to see added to the CMake Tools extension.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: |
      Optionally provide other information that will give us more context about the feature you are requesting.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
