# ==================================================================================
# Pipeline for VsCodeExtension-Localization build definition
# Runs OneLocBuild task to localize xlf file
# ==================================================================================

resources:
  repositories:
  - repository: self
    clean: true
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

trigger: none
pr: none
schedules:
- cron: "0 7 * * *"
  displayName: Daily 7 AM
  branches:
    include:
    - main
  always: true

variables: 
  TeamName: C++ Cross Platform and Cloud
  Codeql.Language: javascript

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      name: AzurePipelines-EO
      image: AzurePipelinesWindows2022compliantGPT
      os: windows
    sdl:
      sourceAnalysisPool: 
        name: AzurePipelines-EO
        image: AzurePipelinesWindows2022compliantGPT
        os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: job
        templateContext:
          outputs:
          - output: pipelineArtifact
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifactName: 'drop'
            publishLocation: 'Container'
        steps:
        - task: CmdLine@2
          inputs:
            script: 'yarn install'
        
        - task: CmdLine@2
          inputs:
            script: 'yarn run translations-export'
        
        - task: OneLocBuild@2
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          inputs:
            locProj: 'jobs/loc/LocProject.json'
            outDir: '$(Build.ArtifactStagingDirectory)'
            isCreatePrSelected: false
            prSourceBranchPrefix: 'locfiles'
            packageSourceAuth: 'patAuth'
            patVariable: '$(OneLocBuildPat)'
            LclSource: lclFilesfromPackage
            LclPackageId: 'LCL-JUNO-PROD-VCMAKE'
            lsBuildXLocPackageVersion: '7.0.30510'
        
        - task: CmdLine@2
          inputs:
            script: 'node ./translations_auto_pr.js microsoft vscode-cmake-tools csigs $(csigsPat) csigs csigs@users.noreply.github.com "$(Build.ArtifactStagingDirectory)/loc" vscode-extensions-localization-export/vscode-extensions'