# ==================================================================================
# Pipeline for VsCodeExtension-Localization build definition
# Gets translated files from VSCodeExt and creates a PR for vscode-cpptools
#
# Triggered only by daily schedule
# ==================================================================================

trigger: none
pr: none
schedules:
- cron: "0 7 * * *"
  displayName: Daily 7 AM
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  path: s/vscode-cmake-tools

- task: CmdLine@2
  inputs:
    script: 'git clone $(LocRepoUri) ..\VSCodeExt'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  inputs:
    script: 'yarn install'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  inputs:
    script: 'node ./translations_auto_pr.js microsoft vscode-cmake-tools cmake-tools csigs $(csigsPat) csigs csigs@users.noreply.github.com $(Build.SourcesDirectory)/../VSCodeExt'
    workingDirectory: '$(Build.SourcesDirectory)'
