# ==================================================================================
# Pipeline for VsCodeExtension-Localization build definition
# Runs OneLocBuild task to localize xlf file
# ==================================================================================

resources:
  repositories:
  - repository: self
    clean: true

trigger: none
pr: none
schedules:
- cron: "0 7 * * *"
  displayName: Daily 7 AM
  branches:
    include:
    - develop
  always: true

pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  inputs:
    script: 'yarn install'

- task: CmdLine@2
  inputs:
    script: 'yarn run translations-export'

- task: OneLocBuild@2
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    locProj: 'jobs/loc/LocProject.json'
    outDir: '$(Build.ArtifactStagingDirectory)'
    isCreatePrSelected: false
    prSourceBranchPrefix: 'locfiles'
    packageSourceAuth: 'patAuth'
    patVariable: '$(OneLocBuildPat)'
    LclSource: lclFilesfromPackage
    LclPackageId: 'LCL-JUNO-PROD-VCMAKE'
    isUseLfLineEndingsSelected: true
    lsBuildXLocPackageVersion: '7.0.30510'

- task: CmdLine@2
  inputs:
    script: 'node ./translations_auto_pr.js microsoft vscode-cmake-tools csigs $(csigsPat) csigs csigs@users.noreply.github.com "$(Build.ArtifactStagingDirectory)/loc" vscode-extensions-localization-export/vscode-extensions'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
