# ==================================================================================
# Release Pipeline for release
# ==================================================================================

name: OfficialRelease-$(Date:yyyyMMdd).$(Rev:r)
trigger: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  pipelines:
  - pipeline: BuildReleasePipeline
    source: '\VC\VSCode\CMakeTools\vscode-cmake-tools - release [YAML]'
    trigger: true

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES

    stages:
    - stage: Validate
      jobs:
        - job: UpdateBuildNumber
          displayName: Update Build Number
          steps:
            - download: BuildReleasePipeline
              artifact: vsix
            - powershell: |
                $newVersion = Get-Content -Path $(Pipeline.Workspace)\BuildReleasePipeline\vsix\version.txt
                Write-Host "New version is: $newVersion"

                $str = Get-Date -Format "yyMMdd-HHmm"
                Write-Host "##vso[build.updatebuildnumber]$newVersion - $str"
              ignoreLASTEXITCODE: true
              displayName: "Set the release name"
        - job: WaitForValidation
          displayName: Wait for vscode-cmake-tools validation
          dependsOn: UpdateBuildNumber
          pool: server
          steps:
            - task: ManualValidation@0
              displayName: "Manual Validation"
              inputs:
                notifyUsers: $(EmailAddress)
                instructions: |
                  Download and test the vsix with the matching version number from the latest release build: $(BuildPipelineURL)

                  The version should match the name of this release.

    - stage: Release
      dependsOn: Validate
      condition: succeeded('Validate')
      jobs:
      - job: ReleaseCMakeTools
        displayName: Release vscode-cmake-tools Tools
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact
            pipeline: BuildReleasePipeline
            artifactName: vsix
            targetPath: $(Build.StagingDirectory)\vsix

        steps:
        - task: NodeTool@0
          displayName: 'Use Node 20.x'
          inputs:
            versionSpec: 20.x
        - script: npm install -g @vscode/vsce
          displayName: 'install vsce'
        - task: AzureCLI@2
          displayName: 'Generate AAD_TOKEN'
          inputs:
            azureSubscription: '$(AzureSubscription)'
            scriptType: ps
            scriptLocation: inlineScript
            inlineScript: |
              $aadToken = az account get-access-token --query accessToken --resource $(AzureGuid) -o tsv
              Write-Host "##vso[task.setvariable variable=AAD_TOKEN;issecret=true]$aadToken"
        - script: |
            vsce publish --packagePath $(Build.StagingDirectory)\vsix\cmake-tools.vsix --manifestPath $(Build.StagingDirectory)\vsix\extension.manifest --signaturePath $(Build.StagingDirectory)\vsix\extension.signature.p7s
          displayName: 'Publish the VSIX'
          env:
            VSCE_PAT: $(AAD_TOKEN)

