# ==================================================================================
# Release Pipeline for release
# ==================================================================================

name: OfficialRelease-$(Date:yyyyMMdd).$(Rev:r)
trigger: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  pipelines:
  - pipeline: BuildReleasePipeline
    source: '\VC\VSCode\CMakeTools\vscode-cmake-tools - release [YAML]'
    trigger: true

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES

    stages:
    - stage: release
      jobs:
      - job: release
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact
            pipeline: BuildReleasePipeline
            artifactName: vsix

        steps:
        - powershell: |
            $newVersion = Get-Content -Path build\vsix\version.txt
            Write-Host "New version is: $newVersion"
            
            $str = Get-Date -Format "yyMMdd-HHmm"
            Write-Host "##vso[release.updatereleasename]$newVersion - $str"
          ignoreLASTEXITCODE: true
          displayName: 'Set the release name'
        - task: ManualIntervention@8
          displayName: 'Manual Intervention'
          inputs:
            instructions: |
              Download and test the vsix from the latest release build: https://devdiv.visualstudio.com/DevDiv/_build?definitionId=17431
              
              The version should match the name of this release.
        - task: NodeTool@0
          displayName: 'Use Node 14.x'
          inputs:
            versionSpec: 14.x
        - task: Npm@0
          displayName: 'install vsce'
          inputs:
            arguments: '-g vsce'
        - task: AzureCLI@2
          displayName: 'Generate AAD_TOKEN'
          inputs:
            azureSubscription: '$(AzureSubscription)'
            scriptType: ps
            scriptLocation: inlineScript
            inlineScript: |
              $aadToken = az account get-access-token --query accessToken --resource $(AzureGuid) -o tsv
              Write-Host "##vso[task.setvariable variable=AAD_TOKEN;issecret=true]$aadToken"
        - script: |
            vsce publish --packagePath build\vsix\cmake-tools.vsix
          displayName: 'Publish the VSIX'
          env:
            VSCE_PAT: $(AAD_TOKEN)

