parameters:
  name: ''
  pool: ''

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: NodeTool@0
    displayName: 'Use Node 10.16.x'
    inputs:
      versionSpec: 10.16.x

  - script: yarn install
    displayName: "Install Dependencies"
    workingDirectory: '$(Build.SourcesDirectory)'

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
    continueOnError: true
