# ==================================================================================
# Pipeline for release
# ==================================================================================

parameters:
- name: signType
  displayName: Signing Type
  type: string
  default: real
  values:
    - test
    - real
- name: VerifyChangelog
  displayName: Attest that CHANGELOG.md is up-to-date.
  type: string
  default: no
  values:
    - yes
    - no
- name: VerifyNotice
  displayName: Attest that all NOTICE files are up-to-date.
  type: string
  default: no
  values:
    - yes
    - no
- name: ReleaseVersion
  displayName: Release Version to set in the vsix package
  type: string
  default: unset

trigger: none

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/rel
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

name: $(Date:yyyyMMdd).$(Rev:r)

variables:
  IsPreRelease: 0
  # ReleaseVersion is set in the versions tab so it can be edited.
  # VerifyNotice is set in the versions tab so it can be edited.
  # VerifyChangelog is set in the versions tab so it can be edited.
  TeamName: C++ Cross Platform and Cloud
  Codeql.Language: javascript

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    sdl:
      sourceAnalysisPool:
        name: VSEngSS-MicroBuild2022-1ES
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: verify_parameters
      jobs:
      - job: verify
        steps:
        - checkout: none
        # Introduce pipeline compilation errors to block scheduling if the requisite parameters are not set
        - ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}
          -'This pipeline can only be run on a release branch.'

    - stage: stage
      jobs:
      - job: Job_1
        displayName: Build release
        templateContext:
          mb: # Enable the MicroBuild Signing toolset
            signing:
              enabled: true
              signType: ${{ parameters.signType }}
              zipSources: false
              ${{ if eq(parameters.signType, 'real') }}:
                signWithProd: true
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish VSIX'
            targetPath: $(Build.ArtifactStagingDirectory)/vsix
            artifactName: vsix
            sbomBuildDropPath: $(Build.ArtifactStagingDirectory)
        steps:
        - checkout: self
          clean: true
          fetchTags: false
        - ${{ if not(eq(parameters.VerifyChangelog, 'yes')) }}:
          - 'CHANGELOG.md should be updated before scheduling the pipeline.'
        - ${{ if not(eq(parameters.VerifyNotice, 'yes')) }}:
          - 'Third party notices should be updated before scheduling the pipeline.'
        - ${{ if eq(parameters.ReleaseVersion, 'unset') }}:
          - 'ReleaseVersion needs to be set before scheduling the pipeline.'
        - template: /jobs/shared/build.yml@self
          parameters:
            ReleaseVersion: ${{ parameters.ReleaseVersion }}
            signType: ${{ parameters.signType }}