name: Build VSIX

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '22'
          check-latest: true

      - name: Get Short SHA
        id: get-short-sha
        run: echo "sha=$(git rev-parse --short ${GITHUB_SHA})" >> $GITHUB_OUTPUT

      - name: Update the package version
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "\"version\": \"(\\d+\\.\\d+\\.\\d+)\""
          replace: "\"version\": \"$1-${{ steps.get-short-sha.outputs.sha }}\""
          include: "package.json"
          exclude: ".git"

      - name: Build the VSIX
        run:  |
          yarn install
          yarn run compile-production
          yarn run package

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cmake-tools.vsix
          path: ./cmake-tools.vsix
          if-no-files-found: error
