name: Build VSIX

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Setup Node.js environment
        uses: actions/setup-node@c6fd00ceb9747fb23ffdf72987450a2664414867 # v2.1.2
        with:
          node-version: '22'
          check-latest: true

      - name: Get Short SHA
        id: get-short-sha
        run: echo "sha=$(git rev-parse --short ${GITHUB_SHA})" >> $GITHUB_OUTPUT

      - name: Update the package version
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "\"version\": \"(\\d+\\.\\d+\\.\\d+)\""
          replace: "\"version\": \"$1-${{ steps.get-short-sha.outputs.sha }}\""
          include: "package.json"
          exclude: ".git"

      - name: Build the VSIX
        run:  |
          yarn install
          yarn run compile-production
          yarn run package

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: cmake-tools.vsix
          path: ./cmake-tools.vsix
          if-no-files-found: error
