name: Locker
on:
  workflow_dispatch:
   inputs:
     readonly:
       description: "readonly: Specify true or 1 to prevent changes from being commited to GitHub"
       default: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: Install Actions
        run: cd ./.github/actions && npm install --production && cd ../..
      - name: Run Locker
        uses: ./.github/actions/locker
        with:
          readonly: ${{ github.event.inputs.readonly }}
          daysSinceClose: 45
          daysSinceUpdate: 3
          ignoreLabels: more votes needed
