name: More Info Needed Closer
on:
  workflow_dispatch:
   inputs:
     readonly:
       description: "readonly: Specify true or 1 to prevent changes from being commited to GitHub"
       default: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
      - name: Install Actions
        run: cd ./.github/actions && npm install --production && cd ../..
      - name: More Info Needed Closer
        uses: ./.github/actions/staleCloser
        with:
          readonly: ${{ github.event.inputs.readonly }}
          labels: more info needed
          closeDays: 60
          closeComment: "This issue has been closed automatically because it needs more information and has not had recent activity."
          pingDays: 80
          pingComment: "Hey @${assignee}, this issue might need further attention.\n\n@${author}, you can help us out by closing this issue if the problem no longer exists, or adding more information."
